platform :ios, '8.0'
use_frameworks!

target 'PodDemo' do
  pod 'HRSigningContract' , :path => '../'
  # pod 'HRBocSignContract'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ARCHS'] = "arm64e arm64 armv7 armv7s"
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end


