platform :ios, '8.0'
use_frameworks!

target 'SignDemo' do
  #pod 'HRSigningContract' , :path => '../'
  pod 'HRSigningContract',:git=>'https://github.com/bizhanlu/HRSigningContract.git',:tag=>'1.2.3.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ARCHS'] = "arm64 armv7"
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end


